// <auto-generated />
namespace BigSchool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Khoitaochucnangdangnhapdangky : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Khoitaochucnangdangnhapdangky));
        
        string IMigrationMetadata.Id
        {
            get { return "202303100149193_Khoi tao chuc nang dang nhap dang ky"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
